# Generated by jeweler, edited later by hand.

Gem::Specification.new do |spec|
  spec.name = "jekyll-org".freeze
  spec.version = "1.1.1"

  spec.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if spec.respond_to? :required_rubygems_version=
  spec.require_paths = ["lib".freeze]
  spec.authors = ["eggcaker".freeze]
  spec.date = "2019-12-14"
  spec.description = "So you want org-mode support for Jekyll. Write your _posts in org-mode, then add 'gems: [jekyll-org]' to your _config.yml. Thats it!".freeze
  spec.email = "eggcaker@gmail.com".freeze
  spec.extra_rdoc_files = [
    "LICENSE",
    "README.org"
  ]
  spec.files = [
    "Gemfile",
    "LICENSE",
    "README.org",
    "Rakefile",
    "VERSION",
    "jekyll-org.gemspec",
    "lib/jekyll-org.rb",
    "lib/jekyll-org/converter.rb",
    "lib/jekyll-org/utils.rb",
    "script/bootstrap",
    "script/cibuild",
    "script/console",
    "script/release",
    "spec/helper.rb",
    "spec/test_jekyll-org.rb"
  ]
  spec.homepage = "http://eggcaker.github.io/jekyll-org".freeze
  spec.licenses = ["MIT".freeze]
  spec.rubygems_version = "3.0.3".freeze
  spec.summary = "Jekyll converter for org-mode files".freeze

  spec.add_dependency(%q<org-ruby>.freeze, [">= 0.9.12"])
  spec.add_dependency(%q<jekyll>.freeze, [">= 3.5.0"])
  spec.add_dependency(%q<json>.freeze, [">= 0"])

  spec.add_development_dependency(%q<shoulda>.freeze, [">= 3.5.0"])
  spec.add_development_dependency(%q<rspec>.freeze, [">= 3.5.0"])
  spec.add_development_dependency(%q<rdoc>.freeze, [">= 3.12"])
  spec.add_development_dependency(%q<bundler>.freeze, [">= 1.0"])
  spec.add_development_dependency(%q<simplecov>.freeze, [">= 0.12.0"])
end
